# if you dont specify locked attribute, the default value will be true
# which means the particular config will be locked
- name: INSTALLATION_NAME
  value: 'Cyberchat'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: BRAND_URL
  value: 'https://chat.cyber1s.com'
- name: WIDGET_BRAND_URL
  value: 'https://chat.cyber1s.com'
- name: BRAND_NAME
  value: 'Cyberchat'
- name: TERMS_URL
  value: 'https://chat.cyber1s.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://chat.cyber1s.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
  locked: false
- name: MAILER_SUPPORT_EMAIL
  value:
  locked: false
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
  locked: false
- name: INSTALLATION_EVENTS_WEBHOOK_URL
  value:
  locked: false
- name: CYBERCHAT_INBOX_TOKEN
  value:
  locked: false
- name: CYBERCHAT_INBOX_HMAC_KEY
  value:
  locked: false
- name: API_CHANNEL_NAME
  value:
- name: API_CHANNEL_THUMBNAIL
  value:
- name: ANALYTICS_TOKEN
  value:
- name: ANALYTICS_HOST
  value:
- name: DIRECT_UPLOADS_ENABLED
  value: false
  locked: false
- name: HCAPTCHA_SITE_KEY
  value:
  locked: false
- name: HCAPTCHA_SERVER_KEY
  value:
  locked: false
- name: LOGOUT_REDIRECT_LINK
  value: /app/login
  locked: false
- name: DISABLE_USER_PROFILE_UPDATE
  value: false
  locked: false
